version: "1.0"
services:
  database:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: petdb
      MYSQL_USER: pet_admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306
    #    volumes:
    #      - ./mysql/conf.d:/etc/mysql/conf.d
    #    command:
    #      - "mysqld"
    #      - "--character-set-server=utf8mb4"
    #      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - pet_network
  application:
    container_name: pet-be
    restart: no
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3307/petdb
      SPRING_DATASOURCE_USERNAME: pet_admin
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - database
    networks:
      - pet_network

networks:
  pet_network: