server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: info
        type: info