server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/petdb
    username: pet_admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true